name: Build Blog

on:
  push:
    branches: [main]
    paths: ["blogs/**/*.md"]

jobs:
  build:
    name: Deploy the Blog
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: curl -fsSL -X POST ${{ secrets.VERCEL_WEBHOOK_URL }} | jq
